app1/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('calculator/', views.calc),
    path('examples/', views.examples),
    path('book-info/<int:id>', views.book_info),
    path('all-books-for-author/<int:id_author>', views.all_books_for_author),
]
# url(r'^about$')

client_app/urls.py
from django.urls import path, include, re_path
from . import views, auth_views

app_name = 'client'

urlpatterns = [
    path('show-book/<int:pk>', views.book_info, name='book-info'),
    path('filters', views.filters, name='filters'),
    path('html', views.html_example),
    path('category-<int:pk>', views.filter_by_category),
    path('cabinet', views.cabinet, name='cabinet'),
    path('return-json', views.return_json),
    # path('login/', auth_views.login_, name='login'),
    # path('logout', auth_views.logout_, name='logout'),
    path('calculator', views.calculator),
    path('demo-model-form', views.demo_model_form, name='demo-model-form'),
    path('privatbank-api', views.api_privatbank, name='privatbank-api'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('write_post', views.write_post, name='write_post'),
    path('delete_article-<int:pk>', views.delete_article, name='delete_article'),
    path('articles-user', views.articles_user, name='articles-user'),
    path('article/<int:pk>', views.article, name='article'),
    path('add-comment/<int:article_id>', views.add_comment, name='add_comment'),
    path('update_article/<int:pk>',
         views.update_article,
         name='update_article'),
]

auth_urls = [
    path('login-form/', auth_views.login_, name='login'),
    path('rgister-form/', auth_views.register_, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.activate, name='activate'),
    path('logout', auth_views.logout_, name='logout'),
]

urlpatterns += auth_urls

eshop_book/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

handler_404 = '404.html'
# handler_500 = '404.html'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('client/', include('client_app.urls', namespace='client')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)
# url(r'^/about$')

eshop_book/templates/includes/header.html
<header>
    <a class="{% if current_tab == 'home' %}active {% endif %}" href="/">Home page</a>
    <a class="{% if current_tab == 'calc' %}active {% endif %}" href="/calculator/">Calculator</a>
    <a href="#">About</a>
    <a href="#">Contacts</a>
    <a class="{% if current_tab == 'examples' %}active {% endif %}" href="/examples/">examples</a>
    <a href="{% url 'client:articles-user' %}">Статьи от пользоватеей</a>

    <a class="btn btn-info" href="{% url 'client:cabinet' %}">Мой кабинет</a>

    {% if request.user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'client:logout' %}">Выход({{ request.user.username }})</a>
    {% else %}
        <a href="{% url 'client:login' %}" class="btn btn-success">Вход</a>
        <a href="{% url 'client:register' %}" class="btn btn-primary">Регистрация</a>
    {% endif %}


</header>