app1/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('calculator/', views.calc),
    path('examples/', views.examples),
    path('book-info/<int:id>', views.book_info),
    path('all-books-for-author/<int:id_author>', views.all_books_for_author),
]
# url(r'^about$')

client_app/urls.py
from django.urls import path, include, re_path
from . import views, auth_views

app_name = 'client'

urlpatterns = [
    path('show-book/<int:pk>', views.book_info, name='book-info'),
    path('filters', views.filters, name='filters'),
    path('html', views.html_example),
    path('category-<int:pk>', views.filter_by_category),
    path('cabinet', views.cabinet, name='cabinet'),
    path('return-json', views.return_json),
    # path('login/', auth_views.login_, name='login'),
    # path('logout', auth_views.logout_, name='logout'),
    path('calculator', views.calculator),
    path('demo-model-form', views.demo_model_form, name='demo-model-form'),
    path('privatbank-api', views.api_privatbank, name='privatbank-api'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('write_post', views.write_post, name='write_post'),
    path('delete_article-<int:pk>', views.delete_article, name='delete_article'),
    path('articles-user', views.articles_user, name='articles-user'),
    path('article/<int:pk>', views.article, name='article'),
    path('add-comment/<int:article_id>', views.add_comment, name='add_comment'),
    path('update_article/<int:pk>',
         views.update_article,
         name='update_article'),
]

auth_urls = [
    path('login-form/', auth_views.login_, name='login'),
    path('rgister-form/', auth_views.register_, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.activate, name='activate'),
    path('logout', auth_views.logout_, name='logout'),
]

urlpatterns += auth_urls

eshop_book/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

handler_404 = '404.html'
# handler_500 = '404.html'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('client/', include('client_app.urls', namespace='client')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)
# url(r'^/about$')

client_app/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.

class Author(models.Model):
    TYPE_USER_VIEW = (
        ('fio', 'ФИО'),
        ('pseudo_name', 'Псевдоним'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(max_length=5000,
                           verbose_name=('Bio'),
                           blank=True, null=True)
    type_view = models.CharField(max_length=255,
                                 verbose_name=('Тип представления'),
                                 choices=TYPE_USER_VIEW,
                                 blank=True, null=True)
    pseudoname = models.CharField(max_length=255,
                                  verbose_name=('Псевдоним'),
                                  blank=True, null=True)

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class Comment(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE)
    msg = models.TextField(max_length=1000, verbose_name='Текст комментария')


class Article(models.Model):
    PUSBLISH_STATUS = (
        ('publish', 'Да'),
        ('unpublish', 'Нет'),
    )
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=255,
                             verbose_name='Title', blank=True,
                             null=True, default='')
    content = RichTextUploadingField()
    create_at = models.DateTimeField(auto_created=True, auto_now_add=True)
    status = models.CharField(max_length=55, verbose_name='Publish?', choices=PUSBLISH_STATUS)
    comments = models.ManyToManyField(Comment)

    def __str__(self):
        return '{} {} '.format(self.title, self.create_at)

    def __repr__(self):
        return 'this is object in sqlite data base with unique id {}'.format(self.id)


class Demo(models.Model):
    name = models.CharField(max_length=255)
    int_examples = models.IntegerField(blank=True, null=True, default=0)
    float_examples = models.FloatField(blank=True, null=True, default=0.0)
    txt_examples = models.TextField(blank=True, null=True, default='')
    date_examples = models.DateField(blank=True, null=True, default='1995-05-12')
    date_time_examples = models.DateTimeField(auto_now_add=True,
                                              blank=True, null=True)
    bool_examples = models.BooleanField(blank=True, null=True, default=True)

    def __str__(self):
        return '{}'.format(self.name)

client_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from client_app.models import Author, Article, Comment

from app1.models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        # fields = ['desc']
        exclude = ['file', 'img']


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    def save(self, *args, **kwargs):
        django_user = User.objects.create_user(username=self.cleaned_data['username'],
                                               first_name=self.cleaned_data['first_name'],
                                               last_name=self.cleaned_data['last_name'],
                                               password=self.cleaned_data['password1'],
                                               email=self.cleaned_data['email'],
                                               is_staff=True,
                                               is_active=False if kwargs['check_mail'] else True
                                               )
        Author.objects.create(user=django_user)
        return django_user

    def get_cleaned_data(self, *args, **kwargs):
        return self.cleaned_data

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        # fields = "__all__"
        exclude = ('user',)
        # widgets = {
        #     'date_birth': forms.DateInput(format=('%m/%d/%Y'),
        #                                   attrs={'class': 'form-control',
        #                                          'placeholder': 'Select a date',
        #                                          'type': 'text'}),
        # }


class ArticleForm(forms.ModelForm):

    def save(self, *args, **kwargs):
        self.instance.author = kwargs['author']
        self.instance.save()

    class Meta:
        model = Article
        exclude = ['author', 'create_at', 'comments']


class CommentForm(forms.ModelForm):

    def save(self, commit=False, *args, **kwargs):
        print(self.instance)
        self.instance.from_user = kwargs['from_user']
        print('save comment!!!!!')
        print(kwargs['from_user'])
        self.instance.save()
        return self.instance

    class Meta:
        model = Comment
        exclude = ['from_user']


from .models import Demo


class DemoForm(forms.ModelForm):
    class Meta:
        model = Demo
        # fields = '__all__'
        fields = ('name', 'bool_examples')
        # exclude = ['name' , 'bool_examples']

client_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from app1.models import Book
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import Author
from .forms import AuthorForm

# Create your views here.
from django.contrib.auth.models import User


@login_required(redirect_field_name=settings.LOGIN_URL)
def cabinet(request):
    ctx = {}
    ctx['cabinet_tab'] = 'main'
    if request.method == 'GET':
        try:
            author = Author.objects.get(user=request.user.id)
            ctx['form'] = AuthorForm(instance=author)
        except Exception as e:
            ctx['form'] = AuthorForm
    elif request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = Author.objects.get(user=request.user.id)
            author.date_birth = form.cleaned_data['date_birth']
            author.bio = form.cleaned_data['bio']
            author.type_view = form.cleaned_data['type_view']
            author.pseudoname = form.cleaned_data['pseudoname']
            author.save()
            ctx['save'] = True
            ctx['form'] = AuthorForm(instance=author)
        else:
            ctx['form'] = AuthorForm(request.POST)
    return render(request, 'client_app/cabinet.html', ctx)


def index(request):
    all_books = Book.objects.all()  # 'SELECT * FROM wa_1_book;'
    return render(request, 'pages/home.html', {
        'a': 'Hello django!',
        'all_books': all_books,
    })


def about(request):
    return render(request, 'pages/about.html', {})


def book_info(request, pk):
    ctx = {}
    ctx['book'] = Book.objects.get(pk=pk)
    return render(request, 'pages/book_info.html', ctx)


import datetime


def filter_by_category(request, pk):
    all_books_in_category = Book.objects.filter(category__id=pk)
    return render(request, 'pages/home.html', {

        'all_books': all_books_in_category,
    })


def filters(request):
    ctx = {}
    ctx['some_text'] = 'lORem ipSum'
    ctx['var'] = 'rrrrrr'
    ctx['number'] = 5
    ctx['first_list'] = range(40)
    ctx['second_list'] = Book.objects.all()
    ctx['x'] = 1
    # if var == 'a':
    #     pass
    # elif var == 'b':
    #     pass
    # else:
    #     pass
    people = [
        {'first_name': 'George', 'last_name': 'Bush', 'gender': 'Male'},
        {'first_name': 'Bill', 'last_name': 'Clinton', 'gender': 'Male'},
        {'first_name': 'Margaret', 'last_name': 'Thatcher', 'gender': 'Female'},
        {'first_name': 'Condoleezza', 'last_name': 'Rice', 'gender': 'Female'},
        {'first_name': 'Pat', 'last_name': 'Smith', 'gender': 'Unknown'},
    ]
    ctx['people'] = people
    ctx['date'] = datetime.datetime.now()
    return render(request, 'partials/filters.html', ctx)


def html_example(request):
    # from .calc import calc_obj
    # ctx = {
    #     'operations': calc_obj.keys()
    # }
    # if request.GET.get('hidden_value'):
    #     try:
    #         first = float(request.GET.get('first_number'))
    #         second = float(request.GET.get('second_number'))
    #         oper = request.GET.get('oper')
    #         result = calc_obj[oper](first, second)
    #         ctx['result'] = result
    #         ctx['first'] = first
    #         ctx['second'] = second
    #     except (ZeroDivisionError, ValueError) as e:
    #         ctx['error'] = e
    return render(request, 'partials/html_example.html', {})


def return_json(request):
    return JsonResponse({
        'status': True,
        'data': {
            'id': 1,
            'name_user': 'admin',
            'password': 'qwerty'
        }
    })


# from .calc import calc_obj


def calculator(request):
    # ctx = {}
    # ctx['operations'] = calc_obj.keys()
    # print(calc_obj.keys())
    return render(request, 'client_app/calculator.html', {})


from .forms import DemoForm


def demo_model_form(request):
    ctx = {}
    form = DemoForm()
    ctx['demo_form'] = form
    if request.method == 'GET':
        ctx['demo_form'] = form
    elif request.method == 'POST':
        form = DemoForm(request.POST)
        if form.is_valid():
            form.save()
            print(form.cleaned_data['name'])
        # print(form.is_valid())
        # print(form)
        print('POOOOST!!!!')
    # print(form)
    return render(request, 'pages/demo_model_form.html', ctx)


import requests


def api_privatbank(request):
    data_from_api = requests.get('https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json')
    print(request.META)
    return render(request, 'pages/privatbank.html', {
        'data': data_from_api.json()
    })


from .models import Article


@login_required(redirect_field_name=settings.LOGIN_URL)
def my_articles(request):
    ctx = {}
    ctx['cabinet_tab'] = 'my_articles'
    aut = Author.objects.get(user=request.user.id)
    ctx['all_articles'] = Article.objects.filter(author=aut)
    return render(request, 'client_app/my_articles.html', ctx)


from .forms import ArticleForm


def write_post(request):
    ctx = {}
    form_article = ArticleForm()
    ctx['form_article'] = ArticleForm()
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            author = Author.objects.get(user=request.user.id)
            form.save(author=author)
            print('valid')
        else:
            ctx['article_form'] = form
            print('invalid')
    return render(request, 'client_app/write_post.html', ctx)


from django.template.loader import render_to_string


def delete_article(request, pk):
    try:
        Article.objects.get(id=pk).delete()
        all_articles = Article.objects.filter(author=Author.objects.get(user=request.user.id))
        new_html = render_to_string('client_app/ajax_reload_articles.html', {
            'all_articles': all_articles
        })
        return JsonResponse({
            'deleted': True,
            'result_html': new_html,
            'new_len': len(all_articles)
        })
    except Exception as e:
        print(e)


def articles_user(request):
    return render(request, 'client_app/articles.html', {
        'articles': Article.objects.filter(status='publish').order_by('-id')
    })


from .forms import CommentForm


def article(request, pk):
    return render(request, 'client_app/article_item.html', {
        'article': Article.objects.get(id=pk),
        'comment_form': CommentForm
    })


def add_comment(request, article_id):
    ctx = {}
    article = Article.objects.get(pk=article_id)
    ctx['article'] = article

    if not request.user.is_authenticated:
        # ctx['article_id'] = article_id
        return render(request, 'client_app/show_article.html', ctx)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            article = Article.objects.get(pk=article_id)
            new_comment = form.save(from_user=request.user)
            article.comments.add(new_comment)
            article.save()
            return redirect('client:article', pk=article_id)
    return redirect('client:article', pk=article_id)


def update_article(request, pk):
    ctx = {}
    current_article = Article.objects.get(id=pk)
    form_update = ArticleForm(instance=current_article)
    # ctx['form_update'] = form_update
    if request.method == 'GET':
        ctx['form_update'] = form_update
        return render(request, 'client_app/update_article.html', ctx)
    elif request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=current_article)
        if form.is_valid():
            author = Author.objects.get(user=request.user.id)
            form.save(author=author)
            return redirect('client:my_articles')

eshop_book/templates/client_app/ajax_reload_articles.html
{% load poll_extras %}
{% for article in all_articles %}
    <div class="js-article alert {{ forloop.counter|set_class }} row"
         data-publish="{{ article.status }}">
        <div class="col-md-1">{{ forloop.counter }}</div>
        <div class="col-md-4">{{ article.title }}</div>
        <div class="col-md-4">{{ article.status }}</div>
        <div class="col-md-3">
            <span class="js-del btn btn-danger"
                  data-url="{% url 'client:delete_article' pk=article.id %}">delete</span>
            <a href="{% url 'client:update_article' pk=article.id %}" class="btn btn-primary">Update</a>
        </div>
    </div>
{% endfor %}

eshop_book/templates/client_app/article_item.html
{% extends 'index.html' %}

{% block content %}

    <h1>{{ article.title }}</h1>
    <div>Author - {{ article.author }} {{ article.create_at }}</div>
    <div>
        {{ article.content|safe }}
    </div>

    <h3>Comments</h3>

    {% if request.user.is_authenticated %}
        <div class="comment-form">
            <form action="{% url 'client:add_comment' article_id=article.id %}" method="POST">
                {% csrf_token %}
                {% for field in comment_form %}
                    <div>
                        <div>{{ field.label_tag }}</div>
                        {{ field }}
                    </div>
                {% endfor %}
                <button class="btn btn-success">Submit</button>
            </form>
        </div>
    {% else %}
        <p class="alert alert-warning">Только для авторизированых пользователей <a
                href="{% url 'client:login' %}">вход</a></p>

    {% endif %}
    {% for comment in  article.comments.all %}

        <div>
            <a href="#">#{{ forloop.counter }}</a>
            <p>От - {{ comment.from_user }}</p>
            <p>{{ comment.msg }}</p>
            <hr>
        </div>

    {% empty %}
        <p class="alert alert-warning">коментариев нет</p>
    {% endfor %}
{% endblock %}

eshop_book/templates/client_app/articles.html
{% extends 'index.html' %}

{% block content %}

    <h1>все статьи от пользователя</h1>
    <div class="row">
        {% for article in articles %}
            <div class="col-md-3">
                <a href="{% url 'client:article' pk=article.id %}">{{ article.title }}</a>
                <p>{{ article.author }}</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

eshop_book/templates/client_app/cabinet.html
{% extends 'index.html' %}
{% block content %}
    <h1>Hello {{ request.user.first_name }} {{ request.user.last_name }} !</h1>

    <div class="cabinet-content row">
        <div class="left-col ">
            <a class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <a class="nav-link {% if cabinet_tab == 'main' %} active {% endif %}"
                   href="{% url 'client:cabinet' %}">Мой
                    профиль</a>
                <a class="nav-link {% if cabinet_tab == 'write_post' %} active {% endif %}"
                   href="{% url 'client:write_post' %}">Написать статью</a>
                <a href="{% url 'client:my_articles' %}"
                   class="nav-link {% if cabinet_tab == 'my_articles' %} active {% endif %}">мои статьи</a>
                {#               href="{% url 'client_app:my_articles' %}">Мои статьи</a>#}
                <a class="nav-link">Подписчики</a>
        </div>
    </div>
    <div class="right-col col-md-9">
        {% if save %}
            <p class="alert alert-success">Успешно сохранили данные!</p>
        {% endif %}
        <div class="content-wrap">
            {% block author_block %}
                <form action="{% url 'client:cabinet' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label }}
                            {{ field }}
                            {% if field.errors %}
                                {{ field.errors }}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button>Save!</button>
                </form>
            {% endblock %}
        </div>
    </div>
    </div>
{% endblock %}

eshop_book/templates/client_app/calculator.html
{% extends 'index.html' %}

{% block content %}
<h1>Calculator!</h1>
{{operations}}
<input type="text">
<select name="oper" id="">
    {% for elem in operations %}
    <option value="{{elem}}">{{elem}}</option>
    {% endfor %}
</select>
<input type="text">

{% endblock %}

eshop_book/templates/client_app/login_form.html
{% extends 'index.html' %}

{% block content %}
<h1>Login!</h1>

<a href="{% url 'client:register' %}">Нет аккаунта?</a>
<form action="{% url 'client:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="text" class="form-control"
               id="exampleInputEmail1" aria-describedby="emailHelp"
               name="username1">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    {% if error %}
    <p class="alert alert-danger">{{error}}</p>
    {% endif %}
</form>


<!--<form>-->
    <!--<div class="form-group">-->
    <!--<label for="exampleInputEmail1">Email address</label>-->
    <!--<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">-->
    <!--<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
    <!--</div>-->
    <!--<div class="form-group">-->
        <!--<label for="exampleInputPassword1">Password</label>-->
        <!--<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">-->
    <!--</div>-->
    <!--<div class="form-check">-->
        <!--<input type="checkbox" class="form-check-input" id="exampleCheck1">-->
        <!--<label class="form-check-label" for="exampleCheck1">Check me out</label>-->
    <!--</div>-->
    <!--<button type="submit" class="btn btn-primary">Submit</button>-->
<!--</form>-->
{% endblock %}

eshop_book/templates/client_app/my_articles.html
{% extends 'client_app/cabinet.html' %}
{% block author_block %}
    <h1>My articles <span class="js-count">{{ all_articles|length }}</span>!</h1>
    <p class="js-sort btn btn-info" data-publish="-1">All</p>
    <p class="js-sort btn btn-info" data-publish="publish">Publish</p>
    <p class="js-sort btn btn-info" data-publish="unpublish">UnPublish</p>
    <div class="article-wrapper">
        <div class="article-row">
            <div class="col-md-1">№</div>
            <div class="col-md-4">Title</div>
            <div class="col-md-4">Publish?</div>
            <div class="col-md-3">Actions</div>
        </div>
        <div id="ajax_reload">
            {% include 'client_app/ajax_reload_articles.html' %}
        </div>

    </div>

    <script>

        $('.js-del').click(function (e) {
            if (confirm('Really?')) {
                let url_send = $(this).data('url');
                $.ajax({
                    method: 'GET',
                    url: url_send
                }).done(function (response) {
                    $('#ajax_reload').html(response.result_html);
                    $('.js-count').html(response.new_len);
                    console.log(response);
                })
                console.log(url_send);
            }
        })

        $('.js-sort').click(function (e) {
            var state_article = $(this).data('publish');
            console.log(state_article);
            if (state_article == -1) {
                $('.js-article').show();
                return;
            }
            var selector = '.js-article[data-publish=' + state_article + ']';
            console.log(selector);
            $('.js-article').hide();
            $(selector).show();
        })
        {#alert($);#}
    </script>
{% endblock %}

eshop_book/templates/client_app/register_form.html
{% extends 'index.html' %}

{% block content %}
    <a href="{% url 'client:login' %}">Есть аккаунт?</a>
    <form method="post" action="{% url 'client:register' %}">
        {% csrf_token %}
        {% for field in form %}
            <p>
                <label for="">{{ field.label }}</label>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </p>
        {% endfor %}
        <label for="">Потверждать почту</label>
        <input type="checkbox" name="check_mail">
        <input type="submit" class="btn btn-success" value="Sign up">
        <input class="btn btn-danger" type="reset" value="reset">

    </form>
{% endblock %}

eshop_book/templates/client_app/update_article.html
{% extends 'client_app/cabinet.html' %}

{% block author_block %}
    <form action="{% url 'client:update_article' form_update.instance.id %}" method="post">
        {% csrf_token %}
        {{ form_update.media }}
        <div>
            {{ form_update }}
        </div>
        <button class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

eshop_book/templates/client_app/write_post.html
{% extends 'client_app/cabinet.html' %}

{% block author_block %}
    <form action="{% url 'client:write_post' %}"
          method="post">
        {% csrf_token %}
        {{ form_article.media }}
        {% for field in form_article %}
            <div>
                <label for="">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    {% for err in field.errors %}
                        <span>{{ err }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        {% endfor %}

        {#        {{ form_article }}#}
        <button>Save</button>
    </form>
{% endblock %}