app1/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('calculator/', views.calc),
    path('examples/', views.examples),
    path('book-info/<int:id>', views.book_info),
    path('all-books-for-author/<int:id_author>', views.all_books_for_author),
]
# url(r'^about$')

client_app/urls.py
from django.urls import path, include, re_path
from . import views, auth_views

app_name = 'client'

urlpatterns = [
    path('show-book/<int:pk>', views.book_info, name='book-info'),
    path('filters', views.filters, name='filters'),
    path('html', views.html_example),
    path('category-<int:pk>', views.filter_by_category),
    path('cabinet', views.cabinet, name='cabinet'),
    path('return-json', views.return_json),
    # path('login/', auth_views.login_, name='login'),
    # path('logout', auth_views.logout_, name='logout'),
    path('calculator', views.calculator),
    path('demo-model-form', views.demo_model_form, name='demo-model-form'),
    path('privatbank-api', views.api_privatbank, name='privatbank-api'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('write_post', views.write_post, name='write_post'),
    path('delete_article-<int:pk>', views.delete_article, name='delete_article'),
    path('articles-user', views.articles_user, name='articles-user'),
    path('article/<int:pk>', views.article, name='article'),
    path('add-comment/<int:article_id>', views.add_comment, name='add_comment'),
    path('update_article/<int:pk>',
         views.update_article,
         name='update_article'),
]

auth_urls = [
    path('login-form/', auth_views.login_, name='login'),
    path('rgister-form/', auth_views.register_, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.activate, name='activate'),
    path('logout', auth_views.logout_, name='logout'),
]

urlpatterns += auth_urls

eshop_book/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

handler_404 = '404.html'
# handler_500 = '404.html'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('client/', include('client_app.urls', namespace='client')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)
# url(r'^/about$')

eshop_book/templates/pages/book_info.html
{% extends 'index.html' %}


{% block title %}
    {{ book.title }}
{% endblock %}


{% block content %}
    <h1 style="text-align: center">{{ book.title }}</h1>
    {% if book.img %}
        <img style="max-width: 350px" src="{{ book.img.url }}" alt="">
    {% endif %}
    <div>
        <p>description - {{ book.description }}</p>
        <p>price - {{ book.price }} $</p>
    </div>
    {% if book.file %}
        <div style="font-size: 48px; color: #ff3fe8;">У нас есть файл для этой книги!</div>
        <a href="{{ book.file.url }}" target="_blank">Read!</a>
    {% endif %}

    <h1>все книги этого автора1</h1>
    <p>{{ book_author }}</p>

    <h3>Можем предложить еще почитать </h3>

    {% for book in book.books_read_with.all %}
        <div>
            <p>id - {{ book.pk }}</p>
            <p>title - {{ book.title }}</p>
            <p>price - {{ book.price }} $</p>
            {#            <p>description - {{ book.description }}</p>#}

            {% if book.img %}
                <p>Здесь есть медиа контент!</p>
            {% endif %}
            <p>author - <a href="/all-books-for-author/{{ book.author.id }}">{{ book.author.author_to_string }}</a></p>
            <a href="/book-info/{{ book.id }}">Show book!</a>
        </div>
    {% endfor %}]
{% endblock %}

eshop_book/templates/pages/calculator.html
{% extends 'index.html' %}

{% block title %}
    Calculator page
{% endblock %}



{% block content %}
    {##}
    {#<div>#}
    {#    text <input type="text">#}
    {#    password <input type="password">#}
    {#    <hr>#}
    {#    number<input type="number">#}
    {#    checkbox<input type="checkbox" checked>#}
    {#    checkbox<input type="checkbox">#}
    {#    checkbox<input type="checkbox">#}
    {#    checkbox<input type="checkbox">#}
    {#    <div>#}
    {#        radio<input type="radio" name="test" checked>#}
    {#        radio1<input type="radio" name="test">#}
    {#        radio2<input type="radio" name="test">#}
    {#        radio3<input type="radio" name="test">#}
    {#        radio4<input type="radio" name="test">#}
    {#        radio5<input type="radio" name="test">#}
    {#    </div>#}
    {#    <div>#}
    {#        select#}
    {#        <select name="" id="">#}
    {#            <option value="">---</option>#}
    {#            <option value="">1</option>#}
    {#            <option value="2">2</option>#}
    {#            <option value="">3</option>#}
    {#        </select>#}
    {#    </div>#}
    {#</div>#}
    <h1>Calculator!</h1>
    <form action="/calculator/" method="post">
        {% csrf_token %}
        <input name="first_num" type="number">
        <select name="operation" id="">
            {% for oper in operations %}
                <option value="{{ oper }}">{{ oper }}</option>
            {% endfor %}
        </select>
        <input name="second_num" type="number">
        <input type="hidden" name="secret_code" value="some value">
        <button>submit!</button>
    </form>

    <p style="color: red; font-size: 48px; font-weight: bold"> {{ msg }}</p>
    <p style="color: green; font-size: 48px; font-weight: bold"> {{ result }}</p>

{% endblock %}





{% block prefooter %}
    <h3>Prefooter block calculator page!!!!</h3>
{% endblock %}

eshop_book/templates/pages/demo_model_form.html
{% extends 'index.html' %}


{% block content %}
    <h1>demo_model_form</h1>

    {#    {{ demo_form.as_ul }}#}
    {#    {{ demo_form.as_p }}#}
    <form action="{% url 'client:demo-model-form' %}" method="post">
        {% csrf_token %}
        {% for field in demo_form %}
            <div>
                <label for="">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button>Submit</button>
    </form>
{% endblock %}

eshop_book/templates/pages/examples.html
{% extends 'index.html' %}
{% load poll_extras %}
{% block title %}
    Examples
{% endblock %}


{% block content %}
    <h1>Examples django templates!</h1>

    {{ bool_value }}

    {% if bool_value %}
        <p style="background: green; padding: 12px;">Bool value is {{ bool_value }}!</p>

    {% else %}
        <p style="background: red; color: white; padding: 12px;">Bool value is {{ bool_value }}!</p>

    {% endif %}


    {% if some_value == 100 %}
        <h1>100!!!!!!</h1>

    {% elif some_value == 150 %}
        <h1>150!!!!!!</h1>
    {% endif %}

    <hr>
    <ol>
        {% for number in some_list %}
            <li>{{ number }}</li>
        {% endfor %}
    </ol>
    <div>
        {{ 'lorem ipsum!'|upper }}
        <p class="alert alert-danger">
            {{ 'lorem SDAASD!'|custom_lower }}
        </p>
    </div>
    <div>
        {{ '355.0'|floatformat:'-3' }}
    </div>

    <a href="{% url 'client:demo-model-form' %}">Model form</a>
    <a href="{% url 'client:privatbank-api' %}">Get privatbank api</a>

    <h1 id="output"></h1>
    Name <input type="text" id="user_input">
    Surname <input type="text" id="user_input_surname">
    <button id="btn">Get full name!</button>
    {#    {{ some_list }}#}


    <script>
        $('#btn').click(function () {
            var name = $('#user_input').val();
            var surname = $('#user_input_surname').val();
            
            $('#output').html(name + ' ' + surname);
        })

        {#var name = 'Anton';#}
        {#var a = 1;#}
        {#var b = 2.6;#}
        {#var t = true;#}
        {#var t2 = false;#}
        {#var l = [1, 2, 3, 4, 5];#}
        {#console.log(a, b, t, t2);#}
        {#var x = confirm('ok?');#}
        {#console.log('2' + 2);#}
        {#console.log('2' - 2);#}
        {#var answer = prompt('>>>> ');#}
        {#console.log(answer);#}
        {##}
        {##}
        {#function f() {#}
        {#    alert('function called!');#}
        {#    for (var i = 0; i < 10; i++) {#}
        {#        if (i % 2 == 0) {#}
        {#            console.log('odd number');#}
        {#            break;#}
        {##}
        {#        } else {#}
        {#            console.log('even number');#}
        {#            continue;#}
        {#        }#}
        {#console.log(i);#}
        {#    }#}
        {#    return;#}

        {##}
        {##}
        {#f();#}
        {#alert('hello js!')#}
    </script>
{% endblock %}

eshop_book/templates/pages/privatbank.html
{% extends 'index.html' %}


{% block content %}
    <h1>Privatbank</h1>
    {#    <ul>#}
    {#        {% for money in data %}#}
    {#            <li>ccy - {{ money.ccy }}#}
    {#                base_ccy - {{ money.base_ccy }}#}
    {#                buy - {{ money.buy }}#}
    {#                sale - {{ money.sale }}#}
    {#            </li>#}
    {#        {% endfor %}#}
    {#    </ul>#}
    {{ data }}
{% endblock %}